## Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [10]:
import numpy as np

#create arrays using numpy
## create a 1d array

arr1=np.array([1,2,3,4,5,])
print(arr1)
print(type(arr1))
print(arr1.shape)  #only 1 number will available as it is 1d array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
arr2=np.array([1,2,3,4,5,])
arr2.reshape(1,5)  #reshape is used to change the shape of the array,now it becomes 2d array


array([[1, 2, 3, 4, 5]])

In [14]:
arr2.reshape(5,1) 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
arr2=np.array([[1,2,3,4,5,]])
arr2.shape

(1, 5)

In [19]:
## 2d array
arr2=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr=np.array([[1,2,3],[4,5,6]])

print("Array:",arr)
print("Array shape:",arr.shape)  #output is 2 rows and 3 columns
print("Array size:",arr.size) #output:2
print("Array dimension:",arr.ndim)   #output:2
print("Array size:",arr.size)    #output:6
print("Array data type:",arr.dtype)    # output:int64 (may vary based on platform)
print("Array item size:",arr.itemsize)    #output:8.  (may vary based on platform)
print("Array total bytes:",arr.nbytes)

Array: [[1 2 3]
 [4 5 6]]
Array shape: (2, 3)
Array size: 6
Array dimension: 2
Array size: 6
Array data type: int64
Array item size: 8
Array total bytes: 48


In [32]:
## Numpy Vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise addition
print("Addition:",arr1+arr2)

#element wise subtraction
print("Subtraction:",arr1-arr2)

#element wise multiplication
print("Multiplication:",arr1*arr2)

#element wise division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [33]:
## Universal function  (function that applies on entire array)
arr=np.array([2,3,4,5,6])

##square root
print(np.sqrt(arr))

##exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [45]:
## array Slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
arr[0][0]
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [49]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [50]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [52]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [ ]:
## Modify array element

arr[0,][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [57]:
arr[1:]=100

np.int64(100)

In [ ]:
## statistical concepts--Normailzation
##to have a mean of 0 and standard deviation of 1

data=np.array([1,2,3,4,5])

# calculate the mean and standard deviation

mean=np.mean(data)
std=np.std(data)

# Normalize the data
normalized_data=(data-mean)/std
print("Normalized data:",normalized_data)

#output:
#Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [60]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean=np.mean(data)
print("Mean:",mean)

#median
median=np.median(data)
print("Median:",median)

#standard deviation
std=np.std(data)
print("Standard Deviation:",std)

#variance
var=np.var(data)
print("Variance:",var)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [66]:
# logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5
data[data>5]
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])